### ISSUE TITLE
Create & deploy auth server

### ISSUE THREAD

**Issue by chyku** [hack4impact-uiuc/mentee#1]
#### Description
Configure h4i auth server for our application so that mentors can log into their profiles. 

#### Tasks
- [ ] Requires scoping out of what we want in a user auth flow.
- [ ] Configuring + deploying to Now
- [ ] Rerouting auth endpoints to auth server (auth.py)
