### ISSUE TITLE
Lock mentor appointment creation to verified mentees

### ISSUE THREAD

**Issue by chyku** [hack4impact-uiuc/mentee#138]
#### Description
Similar to #137 , dependent on #119 . We want to only allow verified mentees to create appointments with mentors

#### Screenshots
When they click "create appt"
![image](https://user-images.githubusercontent.com/10874170/102406741-a631af00-3fb0-11eb-9c35-ea23038b1822.png)

Then goes to actual modal (already implemented):
![image](https://user-images.githubusercontent.com/10874170/102406796-b8135200-3fb0-11eb-8630-2ef27cf28717.png)

#### Tasks
- [ ] Create or use already existing verification modal
- [ ] Link into current appointment creation flow
- [ ] Test & share screenshots of it working
