### ISSUE TITLE
Add admin mentor endpoints

### ISSUE THREAD

**Issue by kenetec** [hack4impact-uiuc/mentee#191]
#### Description
- We need a few admin endpoints that will:
  - delete mentor accounts
  - upload a file that creates whitelisted emails
- These endpoints must be protected, only accessible by an admin account.

#### Files
A list of relevant files for this issue. This will help people navigate the project and offer some clues of where to start. 

#### Tasks
Include specific tasks in the order they need to be done in. Include links to specific lines of code where the task should happen at.
- [ ] Create an admin endpoint for deleting mentor accounts.
- [ ] Create an admin endpoint for uploading a `\n` delimited file that contains an email on every line.
- [ ] Remember that whitelisted emails have a mentee and mentor format. Make sure there is a way for MENTEE to set one "password" for all the mentees.
