### ISSUE TITLE
Create mentor application endpoints

### ISSUE THREAD

**Issue by kenetec** [hack4impact-uiuc/mentee#202]
#### Description
- Right now, mentors are applying through a google form -- let's move this process to our site.
- Create a `MentorApplication` model and endpoints for fetching/deleting objs, and updating fields.
- There should be an `approved` boolean field in the model.

#### Files
A list of relevant files for this issue. This will help people navigate the project and offer some clues of where to start.

#### Tasks
Include specific tasks in the order they need to be done in. Include links to specific lines of code where the task should happen at.
- [x] Create `MentorApplication` model
- [x] Create GET endpoint for fetching application objects.
- [x] Create DELETE endpoint for deleting application objects.
- [x] Create PUT endpoint for updating application objects.
