### ISSUE TITLE
Integrate Mentee Accounts / Refactor Backend

### ISSUE THREAD

**Issue by Leundai** [hack4impact-uiuc/mentee#215]
#### Description
Update the API 🌯 so that it supports the new endpoints along with Mentee Accounts as well!

#### Screenshot Todos
![image](https://user-images.githubusercontent.com/28935000/109580108-b3ded700-7abf-11eb-924e-c074d493e11d.png)
![image](https://user-images.githubusercontent.com/28935000/109579982-7bd79400-7abf-11eb-96fd-fa533c4fffe2.png)

#### Tasks
- [x] Add private field for Mentee Accounts
- [x] Refactor Backend Endpoints/Code
- [x] Integrate into frontend
- [x] Refactor frontend with suggested Kendall tips

**Comment by kenetec** [comment]
Just a quick change, mentees should have the ability to make their profile private so let's add a field in MenteeProfile to denote that

**Comment by kenetec** [comment]
Also can you add a field in `MenteeProfile` for a video link
