### ISSUE TITLE
Create mentee message endpoints

### ISSUE THREAD

**Issue by kenetec** [hack4impact-uiuc/mentee#219]
## Description
Mentors/Mentees need to have the ability to message Mentees. The message schema should contain:
- `message`: string
- `name`: string
- `email`: string
- `link` : string
- `read`: boolean

And any additional information for us to ID who is the sender and who is the receiver.

## Tasks
- [x] Create schema
- [x] Create GET endpoint for retrieving messages
- [x] Create DELETE endpoint for removing messages
- [x] Create PUT endpoint for updating any fields
- [x] Create POST endpoint for creating a message
