### ISSUE TITLE
Design DB structure & create model for mentees' appointment requests

### ISSUE THREAD

**Issue by chyku** [hack4impact-uiuc/mentee#29]
#### Description
Mentees will fill out a form on the frontend to request an appointment with a specific mentor. This will be for a specific time and include the following information:
![image](https://user-images.githubusercontent.com/10874170/96161050-6bda6180-0edc-11eb-8a97-b67c503f4d13.png)

As per the [PRD](https://docs.google.com/document/d/14DHPbMC_1VVO7HG_0sKgJ_gMHOcJxmWx7u0Q4unzbN0/edit).

This will then create a request to the mentor. The different states of a request can be pending, accepted, denied. 

#### Tasks
- [ ] Create DB structure
- [ ] Present to team, get feedback until we get a final structure
- [ ] Implement the model
