### ISSUE TITLE
Figure out what endpoints needed for mentor appointment requests

### ISSUE THREAD

**Issue by chyku** [hack4impact-uiuc/mentee#30]
#### Description
Now that (most of you) know what the different requests are, think about what kinds of endpoints we need for mentees requesting appointments to mentors. Also keep in mind that not every request will contain all the data in a body or return all the data in the db.

Think about the user flow of app- reference the [PRD](https://docs.google.com/document/d/14DHPbMC_1VVO7HG_0sKgJ_gMHOcJxmWx7u0Q4unzbN0/edit) and especially the [designs](https://www.figma.com/file/9macEfYzayWu0k6ogNOUJA/Mentee-Draft-1?node-id=0%3A1). Make sure you (and everyone else!) **understands** what the app is doing and what users' flows will look like. Please, please ask questions if you don't get what's going on!

Then, write issues similar to #3, #6, etc. for each of the required endpoints. *Be sure to note that we want a new view (new file of endpoints) for these requests for code organization purposes*.

#### Tasks
- [ ] Come up with list of endpoints (and verify with team)
- [ ] Understand user flow of the app
- [ ] Write up issues for each of those endpoints (you can group these up if they're similar, i.e. GET all & GET by ID)
