### ISSUE TITLE
Change education to a list of educations

### ISSUE THREAD

**Issue by AngelaLuo49021** [hack4impact-uiuc/mentee#32]
#### Description
Allow mentors to add multiple education objects. 

#### Tasks
- [ ] Update Post Request
- [ ] Update Put Request
- [ ] Make sure there is not broken data in the model
- [ ] Update `Profile.js` to reflect the changes from the database. Look at the TODO comments in the file and change them accordingly
