### ISSUE TITLE
Restrict verified emails to their specific account type

### ISSUE THREAD

**Issue by Leundai** [hack4impact-uiuc/mentee#384]
#### Description
**Backstory**
A Mentee was able to successfully register as a MENTOR instead of a mentor due to clicking the wrong registration form.
Post mortem: We need to restrict their verified emails to whichever they were added to.

Currently Letitia adds new Mentors and Mentees in the provided screenshotted modal. We want to strictly prevent any mentees and mentors to accidentally or purposely sign up as another account type that they weren't planned for.

#### Screenshots
![image](https://user-images.githubusercontent.com/28935000/136324185-5a8ffcaa-6637-4662-a2be-067b116c3506.png)

#### Files
- `verify.py`
- `VerifiedEmail.py`
- `Auth.py`
- `AdminAccountData.js`

#### Tasks
Include specific tasks in the order they need to be done in. Include links to specific lines of code where the task should happen at.
- [ ] Update the existing verified emails model so that it supports a specific account type attribute
- [ ] Update registration flow so that it checks that the email is actually being registered to the correct account type
- [ ] Check that the frontend api calls are able to send information of the type of emails Letitia is hoping to add
- [ ] Test
