### ISSUE TITLE
POST request for mentee appointments 

### ISSUE THREAD

**Issue by AngelaLuo49021** [hack4impact-uiuc/mentee#40]
#### Description
Creation request for mentee appointments
dependent on PR #31 

#### Files
`backend/api/views/appointment.py`
(Create if file does not exist yet)

#### Tasks
- [x] Determine request name, params if necessary, etc.
- [x] Write the request!
- [x] Test it on Postman (check if there's anything in the db first with MongoDB Compass for expected results, and make sure it's not breaking the backend!)
- [x] Create a PR with ^ as screenshots and a description of what you've completed!
