### ISSUE TITLE
Make sidebar responsive

### ISSUE THREAD

**Issue by Leundai** [hack4impact-uiuc/mentee#47]
#### Description
There might be something that is already in Antd that makes things responsive. However, if that isn't the case here is a [guide](https://medium.com/the-innovation/creating-a-responsive-sidebar-in-ant-design-e26c7423789f) on how to make a responsive sidebar specifically for Ant Design.

#### Screenshots
![image](https://user-images.githubusercontent.com/28935000/96749087-fbc25480-138f-11eb-88e2-6e73ff939dc4.png)
![image](https://user-images.githubusercontent.com/28935000/96749759-d71aac80-1390-11eb-800a-f08fcd54d306.png)

#### Resources
[Guide](https://medium.com/the-innovation/creating-a-responsive-sidebar-in-ant-design-e26c7423789f)
[Antd Layout](https://ant.design/components/layout/)

#### Tasks
- [ ] Create responsive layout for sidebar
- [ ] Test it using google's built in tools
- [ ] Update PR with screenshots
