### ISSUE TITLE
Move all CSS constants into a separate file

### ISSUE THREAD

**Issue by chyku** [hack4impact-uiuc/mentee#49]
#### Description
SCSS allows for you to write [variables](https://sass-lang.com/documentation/variables), and then you can [import](https://sass-lang.com/documentation/at-rules/import) the file to use everywhere else.

We want to be able to just import things so the code looks cleaner and we would be able to change colors easily if we want to.

#### Files
You can probably put this in `App.scss` where `App.js` is, I don't have a huge preference

#### Tasks
- [ ] Create scss file for constants

- [ ] Find colors in other current SCSS files (and any others if you can find them in the design) and add them as SCSS variables

- [ ] Import the file in other scss files and replace hardcoded values with variables
