### ISSUE TITLE
POST request for mentor profiles

### ISSUE THREAD

**Issue by chyku** [hack4impact-uiuc/mentee#5]
#### Description
Dependent on #2 
Create a POST (creation) request for mentor profiles. Make sure you know what fields should be optional on creation & what can be added later!

#### Files
`backend/api/views/main.py`

#### Tasks
- [x]  Determine request name, params if necessary, body format, etc.
- [x]  Write the request!
- [x]  Test it on Postman (create a profile, then check its format on Compass. If #3 or #4 are done, you can try calling those!)
- [x] Create a PR with ^ as screenshots and a description of what you've completed!
