### ISSUE TITLE
Endpoint for uploading profile picture

### ISSUE THREAD

**Issue by chyku** [hack4impact-uiuc/mentee#58]
#### Description
We need an endpoint for mentors to specifically upload their profile picture. This should take in an image, hit the [Imgur API](https://apidocs.imgur.com/), upload it, and finally store the Imgur URL.

You can reference the way [YMCA](https://github.com/hack4impact-uiuc/ymca/blob/e1e2445bf5e1c5a94b79a89e1789db2f4eb5af44/api/src/api/admin.js#L8) handled this, but you'll also have to handle setting up our app with Imgur, etc.

#### Files
`views/main.py`

#### Tasks
- [x] Set up Imgur API
- [x] Hit Imgur API in endpoint
- [x] Store uploaded image URL in MentorProfile
- [x] Test on Postman- include the entire flow if you can record your screen (sending the request w/ the image, showing that the img was properly uploaded & the url works and is stored in profile)

**Comment by Leundai** [comment]
![image](https://user-images.githubusercontent.com/28935000/97375957-262d7980-188a-11eb-9eaa-96abc687b028.png)
