### ISSUE TITLE
Set up frontend connection to backend

### ISSUE THREAD

**Issue by chyku** [hack4impact-uiuc/mentee#62]
#### Description
Write functions that call our backend in the frontend. Basically, you'll need to create a file (or files) similar to [the API helpers in LAH](https://github.com/hack4impact-uiuc/life-after-hate/tree/master/frontend/src/utils) or in [YMCA](https://github.com/hack4impact-uiuc/ymca/blob/master/client/src/utils/api.js).

A quick explanation of how these work is the frontend uses a library that calls a backend endpoint- you just plug in the same URL you would use in Postman, but you want to make Javascript do this in code so that you can use it in a component. 

You also want to keep a temporary constant for a mentor ID as I'm trying to get #1 auth working so that you know what mentor ID to pass into some requests.

Make sure you understand [Javascript promises](https://web.dev/promises/)! All API calls will be asynchronous, so you need to know how to get the data out of them.

#### Files
Create an API file in `frontend/src/utils` (if that's a folder idr)

#### Tasks
- [x] Set up API file
- [x] Try testing one endpoint (you can load a page and console.log(request_data))
- [x] Set up the other existing mentor/appointment endpoints in the file

**Comment by Leundai** [comment]
Promises 👉 👈
