### ISSUE TITLE
Create and Translate Training Videos

### ISSUE THREAD

**Issue by Leundai** [hack4impact-uiuc/mentee#720]
#### Description
[This Google Cloud Resource](https://cloud.google.com/community/tutorials/speech2srt) will help a lot with making a job that on submitting a training video we can also transcribe and translate these videos and finally applying them.

#### Tasks
- [ ] Setup project and API Endpoints that can handle submitting video files
- [ ] Setup frontend components for admin uploading videos. (Please display costs for translating these videos too)
- [ ] Either host these videos ourselves or return them back to Letitia so that she can upload them to youtube
