### ISSUE TITLE
Implement auth endpoints

### ISSUE THREAD

**Issue by chyku** [hack4impact-uiuc/mentee#81]
#### Description
Basically do what I was doing in #23 - referencing the code there in `views/auth.py` and the code in [this example repo](https://github.com/hack4impact-uiuc/infra-authentication-api/tree/master/src/api), reroute those endpoints to the auth server. Specifically, reroute the endpoints listed in tasks.

Feel free to reference my PR for how to use those endpoints to create your own user and then test these endpoints

References:
- [General auth server documentation](https://www.notion.so/h4iuiuc/Authentication-Server-12c9fa26d1b9457bb84d7105caea530e)
- [Documentation for resend](https://www.notion.so/h4iuiuc/Verify-Workflow-5a62f4134e2349119aeb6ad2a16a2fc7#c33d72817b09482294b24b5a9f6df86a)
- [Documentation for forgot password flow](https://www.notion.so/h4iuiuc/Forgot-Password-Workflow-3d73303f0a1d423f84478746a1afa20d)

#### Files
`views/auth.py` 

#### Tasks
- [x] resendVerificationEmail.js - this resends a verification email
- [x] forgotPassword.js - this triggers the password reset flow, sending the user an email w/ a pin
- [x] passwordReset.js - this resets the password
