### ISSUE TITLE
Add auth to repo

### ISSUE THREAD

**Issue by chyku** [hack4impact-uiuc/mentee#83]
#### Description
Reminder for myself to add the auth server to this repo

#### Tasks
Include specific tasks in the order they need to be done in. Include links to specific lines of code where the task should happen at.
- [x] Add auth repo to this repo
- [x] Add .env, etc to gitignore
- [x] Add .env actual contents to Slack or in a file on Drive
