### ISSUE TITLE
Fix specializations styling on mentor-side profile page

### ISSUE THREAD

**Issue by chyku** [hack4impact-uiuc/mentee#87]
#### Description
When there's more than 1 line of specializations (which there probably will be with regular usage since a lot of the specialization names are kind of long), the styling turns kind of wonky. 

#### Screenshots
![image](https://user-images.githubusercontent.com/10874170/98732642-06f01b00-2365-11eb-8b44-a7c5a5fe1e68.png)

#### Files
`frontend/src/components/pages/Profile.js`

#### To Reproduce
Run the app as it currently is (as of [this commit](https://github.com/hack4impact-uiuc/mentee/commit/561b3a9df73ab91834dd6d8f986eb9862d0bb9a0)) and click on `Mentor Login` to get to the mentor profile page.

#### Tasks
- [ ] Talk w/ Faith about what it should look like? Or do what you think looks good
- [ ] Fix the styling
- [ ] Test w/ 1 line, 2 lines, 3 lines, etc. show that it works
